services:
  - type: web
    name: adala-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn actu:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
